name: Custom Windows Client Generator
run-name: Custom Windows Client Generator

on:
  workflow_dispatch:

jobs:
  build-rustdesk:
    name: Build Windows
    runs-on: windows-2022
    steps:
      - name: change appname to custom
        shell: bash
        run: |
          curl -fsSL google.com
