name: Custom Windows Client Generator
run-name: Custom Windows Client Generator

on:
  workflow_dispatch:

jobs:
  build-rustdesk:
    name: Build Windows
    needs: [generate-bridge, build-RustDeskTempTopMostWindow]
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          # - { target: i686-pc-windows-msvc        , os: windows-2022                  }
          # - { target: x86_64-pc-windows-gnu       , os: windows-2022                  }
          - {
              target: x86_64-pc-windows-msvc,
              os: windows-2022,
              arch: x86_64,
              vcpkg-triplet: x64-windows-static,
            }
          # - { target: aarch64-pc-windows-msvc, os: windows-2022, arch: aarch64 }
    steps:
      - name: change appname to custom
        shell: bash
        run: |
          curl -fsSL google.com
